cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/add/<str:product_type>/', views.cart_add, name='cart_add'),
    path('cart/remove/<str:product_type>/', views.cart_remove, name='cart_remove'),
    path('cart/clear/', views.clear_cart, name='clear_cart'),
]

maindj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from members import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('users/', include('users.urls', namespace='users')),
    path('social-auth/', include('social_django.urls', namespace='social')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import include, path
from . import views
from .views import SheakersShopView, ShopListView, ShortsShopView, TShirtShopView
from django.views.decorators.cache import cache_page


app_name = 'members'

urlpatterns = [
      path('main/' , cache_page(60)(views.members), name='members'), 
     
      path('pay/', views.pay_system_view, name='pay'),
      path('not-auth/', views.not_auth, name='not_auth'),

      path('shop/', cache_page(10)(ShopListView.as_view()) , name='shop'),
      path('shop/<int:id>/<slug:slug>', views.product_detail_product,
         name='product_detail'),

      path('shop-tshirt/', cache_page(10)(TShirtShopView.as_view()), name='shop_tshirt'),
      path('shop-tshirt/<int:id>/<slug:slug>/', views.product_detail_product_tshirt,
           name='product_detail_tshirt'),

      path('shop-shorts/', cache_page(10)(ShortsShopView.as_view()), name='shop_shorts'),
      path('shop-shorts/<int:id>/<slug:slug>/', views.product_detail_shorts,
           name='product_detail_shorts'),

      path('shop-sneakers/', cache_page(10)(SheakersShopView.as_view()), name='shop_sneakers'),
      path('shop-sneakers/<int:id>/<slug:slug>/', views.product_detail_sneakers,
           name='product_detail_sneakers'),
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import LoginUser, RegisterUser


app_name = 'users'

urlpatterns = [
     path('login/', LoginUser.as_view(), name='login'), 
     path('logout/', LogoutView.as_view(), name='logout'),


     path('password-change/', views.UserPasswordChange.as_view(), name='password_change'), 
     path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name='password_change_done'), 
     path('password-reset/', 
         PasswordResetView.as_view(
            template_name = "users/password_reset_form.html", 
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")
            ),
         name='password_reset'),
     path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"), name='password_reset_done'),
     path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
     path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
         
     path('register/', RegisterUser.as_view(), name='register'), 
     path('profile/', views.ProfileUser.as_view(), name='profile'),
]

members/forms.py
from django import forms
from datetime import date


class PaySystemForm(forms.Form):
  cart_number = forms.IntegerField(label='Номер карты', widget=forms.TextInput(attrs={'class': 'form-input', 'maxlength': '16'}))
  day = forms.DateTimeField(label='День', widget=forms.TextInput(attrs={'class': 'form-input', 'maxlength': '2'}))
  month = forms.DateTimeField(label='Месяц', widget=forms.TextInput(attrs={'class': 'form-input', 'maxlength': '2'}))
  year = forms.DateTimeField(label='Год', widget=forms.TextInput(attrs={'class': 'form-input', 'maxlength': '2'}))
  cvv_number = forms.IntegerField(label='CVV', widget=forms.TextInput(attrs={'class': 'form-input', 'maxlength': '3'}))
  amount = forms.DecimalField(label='Сумма', widget=forms.NumberInput(attrs={'class': 'form-input', 'maxlength': '300'}))
  description = forms.CharField(label='Описание', widget=forms.TextInput(attrs={'class': 'form-input'}))
  token = forms.CharField(widget=forms.HiddenInput())

  def clean_cart_number(self):
    cart_number = self.cleaned_data.get('cart_number')
    if cart_number and len(str(cart_number)) != 16:
        raise forms.ValidationError('Неверный номер карты')
    return cart_number

  def clean_data_number(self):
    cleaned_data = super().clean()
    day = cleaned_data.get('day')
    month = cleaned_data.get('moth')
    year = cleaned_data.get('year')

        # Проверка корректности даты
    try:
      date(year, month, day)
    except ValueError:
      raise forms.ValidationError('Некорректная дата')
    if not len(day) == 2 or len(month) == 2 or len(year) == 2:
        raise forms.ValidationError('Некорректная дата')

    return cleaned_data

  def clean_cvv_number(self):
    cvv_number = self.cleaned_data.get('cvv_number')
    if cvv_number and len(str(cvv_number)) != 3:
      raise forms.ValidationError('Неверное количество символов в CVV')
    return cvv_number

  def clean_amount(self):
    amount = self.cleaned_data.get('amount')
    if amount and amount <= 0:
      raise forms.ValidationError('Сумма должна быть положительной')
    return amount
  

class ColorFilterForm(forms.Form):
    color = forms.CharField(required=False)

members/views.py
from django.forms import ValidationError
from django.views import View
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse
from django.template import loader

from django.core.cache import cache
from django.utils.http import urlencode
from cart.cart import Cart
from .utils import recommend_products
from .models import  Product, Category, ProductShorts, ProductSneakers, ProductTshirt
from cart.forms import CartAddProductForm
from .forms import ColorFilterForm, PaySystemForm
from django.db.models import Q


def members(request):
  template = loader.get_template('all_members.html')
  return HttpResponse(template.render())


def not_auth(request):
  return render(request, 'not_aunt.html')

def product_detail(request, id, slug, model, template_name):
    product = get_object_or_404(model, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    user = request.user
    if not user.is_authenticated:
      return redirect('members:not_auth')
    
    # Передаем информацию о текущем продукте в функцию рекомендаций
    recommended_products = recommend_products(user, product)
    return render(request, template_name, {
        'product': product,
        'cart_product_form': cart_product_form,
        'recommended_products': recommended_products,
    })

def product_detail_product(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return product_detail(request, id, slug, Product, 'detail.html')

def product_detail_product_tshirt(request, id, slug):
    product = get_object_or_404(ProductTshirt, id=id, slug=slug, available=True)
    return product_detail(request, id, slug, ProductTshirt, 'product_detail_thirt.html')

def product_detail_shorts(request, id, slug):
    product = get_object_or_404(ProductShorts, id=id, slug=slug, available=True)
    return product_detail(request, id, slug, ProductShorts, 'product_detail_shorts.html')

def product_detail_sneakers(request, id, slug):
    product = get_object_or_404(ProductSneakers, id=id, slug=slug, available=True)
    return product_detail(request, id, slug, ProductSneakers, 'product_detail_sneakers.html')


class ShopListView(ListView):
    context_object_name = 'products'
    template_name = 'shop.html'
    model = Product
    paginate_by = 9  

    def get_queryset(self):
        selected_brands = self.request.GET.getlist('category')
        selected_color = self.request.GET.getlist('color')
        max_price = self.request.GET.get('price')
        min_price = self.request.GET.get('-price')
        direction = self.request.GET.get('direction')


        cache_key = f"product:{urlencode(self.request.GET)}"
        queryset = cache.get(cache_key)

        if queryset is None:  # Используем `is None`, чтобы убедиться, что queryset не закэширован
            queryset = Product.objects.filter(available=True)
            # Фильтрация по брендам
            if selected_brands:
                queryset = queryset.filter(category__name__in=selected_brands)

            # Фильтрация по цвету
            if selected_color:
                queryset = queryset.filter(color__in=selected_color)

            # Фильтрация по цене
            if min_price is not None:
                queryset = queryset.filter(price__gte=min_price)
            if max_price is not None:
                queryset = queryset.filter(price__lte=max_price)

            # Сортировка по цене
            if direction == 'ascending':
                queryset = queryset.order_by('price')
            elif direction == 'descending':
                queryset = queryset.order_by('-price')
            # Кэшируем результат на 15 минут
            cache.set(cache_key, queryset, 60 * 15)

        return queryset
           
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        categories = set(queryset.values_list('category__name', flat=True))  
        colors = set(queryset.values_list('color', flat=True))# Уникальные категории
        
        # Проверяем, есть ли категории перед их передачей в контекст
        if categories:
            context['categories'] = categories
        else:
            context['categories'] = Product.objects.values_list('category', flat=True).distinct()
        
        if colors:
          context['colors'] = colors
        else:
          context['colors'] = Product.objects.values_list('color', flat=True).distinct()
            
        context['selected_brands'] = self.request.GET.getlist('category')
        context['selected_colors'] = self.request.GET.getlist('color')
        context['max_price'] = self.request.GET.get('max_price')
        context['min_price'] = self.request.GET.get('min_price')
        context['ordering'] = self.request.GET.get('ordering')

        return context
    

class TShirtShopView(ListView):
    context_object_name = 'product_tshirts'
    template_name = 'shop_t-shirt.html'
    model = ProductTshirt
    paginate_by = 9  

    def get_queryset(self):
        selected_brands = self.request.GET.getlist('category')
        selected_color = self.request.GET.getlist('color')
        max_price = self.request.GET.get('price')
        min_price = self.request.GET.get('-price')

        cache_key = f"tshirt_product:{urlencode(self.request.GET)}"
        queryset = cache.get(cache_key)

        if queryset is None:  # Используем `is None`, чтобы убедиться, что queryset не закэширован
            queryset = ProductTshirt.objects.filter(available=True)
            # Фильтрация по брендам
            if selected_brands:
              queryset = queryset.filter(category__name__in=selected_brands)

            # Фильтрация по цвету
            if selected_color:
              queryset = queryset.filter(color__in=selected_color)

            # Фильтрация по цене  
            if min_price and max_price:
              queryset = queryset.filter(price__gte=min_price, price__lte=max_price)

            direction = self.request.GET.get('direction')
            if direction == 'ascending':
              queryset = queryset.order_by('price')
            if direction == 'descending':
              queryset = queryset.order_by('-price')
            # Кэшируем результат на 15 минут
            cache.set(cache_key, queryset, 60 * 15)
            
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        categories = set(queryset.values_list('category__name', flat=True))  
        colors = set(queryset.values_list('color', flat=True))# Уникальные категории
        
        # Проверяем, есть ли категории перед их передачей в контекст
        if categories:
            context['categories'] = categories
        else:
            context['categories'] = ProductTshirt.objects.values_list('category', flat=True).distinct()
        
        if colors:
          context['colors'] = colors
        else:
          context['colors'] = ProductTshirt.objects.values_list('color', flat=True).distinct()
            
        context['selected_brands'] = self.request.GET.getlist('category')
        context['selected_colors'] = self.request.GET.getlist('color')
        context['max_price'] = self.request.GET.get('max_price')
        context['min_price'] = self.request.GET.get('min_price')
        context['ordering'] = self.request.GET.get('ordering')

        return context
    

class ShortsShopView(ListView):
    context_object_name = 'product_shorts'
    template_name = 'shop_shorts.html'
    model = ProductShorts  
    paginate_by = 9  

    def get_queryset(self):
        selected_brands = self.request.GET.getlist('category')
        selected_color = self.request.GET.getlist('color')
        max_price = self.request.GET.get('price')
        min_price = self.request.GET.get('-price')
        direction = self.request.GET.get('direction')

        cache_key = f"shorts_product:{urlencode(self.request.GET)}"
        queryset = cache.get(cache_key)

        if queryset is None:  # Используем `is None`, чтобы убедиться, что queryset не закэширован
            queryset = ProductShorts.objects.filter(available=True)
            # Фильтрация по брендам
            if selected_brands:
                queryset = queryset.filter(category__name__in=selected_brands)

            # Фильтрация по цвету
            if selected_color:
                queryset = queryset.filter(color__in=selected_color)

            # Фильтрация по цене
            if min_price is not None:
                queryset = queryset.filter(price__gte=min_price)
            if max_price is not None:
                queryset = queryset.filter(price__lte=max_price)

            # Сортировка по цене
            if direction == 'ascending':
                queryset = queryset.order_by('price')
            elif direction == 'descending':
                queryset = queryset.order_by('-price')
            # Кэшируем результат на 15 минут
            cache.set(cache_key, queryset, 60 * 15)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        categories = set(queryset.values_list('category__name', flat=True))  
        colors = set(queryset.values_list('color', flat=True))# Уникальные категории
        
        # Проверяем, есть ли категории перед их передачей в контекст
        if categories:
            context['categories'] = categories
        else:
            context['categories'] = ProductShorts.objects.values_list('category', flat=True).distinct()
        
        if colors:
          context['colors'] = colors
        else:
          context['colors'] = ProductShorts.objects.values_list('color', flat=True).distinct()
            

members/templates/all_members.html
{% extends "master.html" %}

{% block title %}
  Wilmar shop
{% endblock %}


{% block content %}
{% if not is_draft.True %}

<h1 class='logotip'></h1>
  <div class="mycard">

    <ul>


      <li  onclick="window.location = '/shop/'"> Sweatshirts </li>
      <a href="{% url 'members:shop_tshirt' %}"><li > T-shirts </li></a>
      <a href="{% url 'members:shop_shorts' %}"><li> Shorts </li></a>
      <a href="{% url 'members:shop_sneakers' %}"><li> Sneakers </li></a>

    </ul>
  </div>
{% endif %}

{% endblock %}

members/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}Мой магазин{% endblock %}</title>
<link href="{% static "shop.css" %}" rel="stylesheet">
</head>
<body>
<div class='headercont'>  
    <p ><a class='back' href="/shop/"> &lt; BACK</a></p>
    <div class='loggo'></div>
  
    <a href='/main/'><img class='loggo' src='/static/img/logobv.png' ></a>
  

</div>


<div id="subheader">
  <div class='cart'>
    {% with total_items=cart|length %}
    {% if cart|length > 0 %}
    <a href={% url 'cart:cart_detail' %}>
      {{ total_items }} шт ,${{ cart.get_total_price }}
    </a>
    {% else %}
    Корзина пустая 
    {% endif %}
    {% endwith %} 
  </div>
</div>
<div id="content">
{% block content %}{% endblock %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
  // При клике на ссылку слайдера
  $(".slider a").click(function(e) {
    e.preventDefault(); // Отменить стандартное поведение ссылки

    var target = $(this).attr("href"); // Получить значение атрибута href
    $(".slide").removeClass("active"); // Удалить класс "active" у всех слайдов
    $(target).addClass("active"); // Добавить класс "active" к выбранному слайду
  });

  // При клике на кнопку "Предыдущий слайд"
  $(".prev-btn").click(function() {
    var currentSlide = $(".slide.active");
    var prevSlide = currentSlide.prev();

    if (prevSlide.length === 0) {
      prevSlide = $(".slide").last();
    }

    currentSlide.removeClass("active");
    prevSlide.addClass("active");
  });

  // При клике на кнопку "Следующий слайд"
  $(".next-btn").click(function() {
    var currentSlide = $(".slide.active");
    var nextSlide = currentSlide.next();

    if (nextSlide.length === 0) {
      nextSlide = $(".slide").first();
    }

    currentSlide.removeClass("active");
    nextSlide.addClass("active");
  });
});
</script>
</html>

members/templates/master.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="{% static 'main.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% if user.is_authenticated %}
  <div class='topnav'>
    <ul>
      
        <a href="{% url 'users:profile' %}">{{ user.username }}</a>
      
      <div class="separator">|</div>
      
        <form action="{% url 'users:logout' %}" method="post">
          {% csrf_token %}
          <button type="submit">Выйти</button>
        </form>
      
    </ul>
  </div>

  {% else %}
    <div class='login-account'><a href={% url 'users:login'%}>Войти в аккаунт</a> |
    <a href={% url 'users:register' %}>Регистрация</a></div>
  {% endif %}
{% block content %}
{% endblock %}

</body>
</html>

members/templates/not_aunt.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="{% static 'shop.css' %}">
</head>
<body>
  {% block content %} 
  <div class='container-pls'>Пожалуйста зарегестрируйтесь, или войдите в аккаунт!</div>
  <div class='container-log'><li class='login-account'><a href={% url 'users:login'%}>Войти в аккаунт</a> |
    <a href={% url 'users:register' %}>Регистрация</a></li></div>
  {% endblock %}
</body>
</html>

members/templates/paysystem.html
{% extends 'master.html' %}
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'main.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>
{% block content %}
<h1 class='pay-title'>Оплата</h1>
<form method="post" class="form-container">
  {% csrf_token %}
  <label class="form-label" for="id_cart_number">Номер карты:</label>
  {{ form.cart_number.errors }}
  {{ form.cart_number }}


  <label class="form-label" for="id_day">День:</label>
  {{ form.day.errors }}
  {{ form.day }}

  <label class="form-label" for="id_month" maxlength="2">Месяц:</label>
  {{ form.data_number.errors  }}
  {{ form.month}}

  <label class="form-label" for="id_year" maxlength="2">Год:</label>
  {{ form.year_number.errors }}
  {{ form.year }}

  <label class="form-label" for="id_cvv_number">CVV:</label>
  {{ form.cvv_number.errors }}
  {{ form.cvv_number }}

  <label class="form-label" for="id_amount">Сумма:</label>
  {{ form.amount.errors }}
  {{ form.amount }}

  <label class="form-label" for="id_description">Описание:</label>
  {{ form.description.errors }}
  {{ form.description }}
  <button type="submit" class="submit-button">Отправить</button>
</form>



<script>
  document.addEventListener('DOMContentLoaded', function() {
    var form = document.querySelector('.form-container');
    form.addEventListener('submit', function(event) {
      var cartNumberInput = document.getElementById('id_cart_number');
      var dayField = document.getElementById("id_day");
      var monthField = document.getElementById("id_month");
      var yearField = document.getElementById("id_year");  
      var cvvNumberInput = document.getElementById('id_cvv_number');
      var amountInput = document.getElementById('id_amount');
  
      // Очищаем предыдущие сообщения об ошибках
      clearErrors();
  
      // Проверка номера карты
      if (cartNumberInput.value.length !== 16) {
        showErrorMessage(cartNumberInput, 'Неверный номер карты');
        event.preventDefault();
        return;
      }

      // Проверка дня
      var day = parseInt(dayField.value);
      if (isNaN(day) || day < 1 || day > 31) {
        showErrorMessage(dayField, 'Неверный день');
        event.preventDefault();
        return;
      }

      // Проверка месяца
      var month = parseInt(monthField.value);
      if (isNaN(month) || month < 1 || month > 12) {
        showErrorMessage(monthField, 'Неверный месяц');
        event.preventDefault();
        return;
      }

      // Проверка года
      var year = parseInt(yearField.value);
      if (isNaN(year) || year < new Date().getFullYear()) {
        showErrorMessage(yearField, 'Неверный год');
        event.preventDefault();
        return;
      }

      // Проверка CVV
      if (cvvNumberInput.value.length !== 3) {
        showErrorMessage(cvvNumberInput, 'Неверное количество символов CVV');
        event.preventDefault();
        return;
      }
  
      // Проверка суммы
      var amount = parseFloat(amountInput.value);
      if (isNaN(amount) || amount <= 0) {
        showErrorMessage(amountInput, 'Сумма должна быть положительной числовой');
        event.preventDefault();
        return;
      }
    });

  
    // Функция для отображения сообщения об ошибке
    function showErrorMessage(input, message) {
      var errorElement = document.createElement('div');
      errorElement.classList.add('error-message');
      errorElement.textContent = message;
      input.parentNode.insertBefore(errorElement, input.nextSibling);
      input.classList.add('invalid');
    }
  
    // Функция для очистки сообщений об ошибках
    function clearErrors() {
      var errorMessages = document.querySelectorAll('.error-message');
      errorMessages.forEach(function(errorMessage) {
        errorMessage.remove();
      });
      var invalidInputs = document.querySelectorAll('.invalid');
      invalidInputs.forEach(function(input) {
        input.classList.remove('invalid');
      });
    }
  });
</script>

{% endblock %}

members/templates/shop.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="{% static 'shop.css' %}">
</head>
<body>
  <div class='mainbody'>
  {% block content %} 
  <div class='headercont'>
    <a class='ahref' href="/main/">Главная</a>
    <a href='/main/'><img class='loggo' src='/static/img/logobv.png' ></a>
    {% if not cart %}
  <a class="cartimg" href='/cart/cart/'>
    <p id='cart-total'>0</p>
  </a>

  {% else %}
  {% for item in cart %}
  <a class="cartimg" href='/cart/cart/'>
    <p id='cart-total'>{{ cart|length }}</p>
  </a>
  {% endfor %}
  {% endif%}
  {% if user.is_authenticated %}

  <div class='topnav'>
    <ul>
      <li>
        <a href="{% url 'users:profile' %}">{{ user.username }}</a>
      </li>
      <li class="separator">|</li>
      <li>
        <form action="{% url 'users:logout' %}" method="post">
          {% csrf_token %}
          <button type="submit">Выйти</button>
        </form>
      </li>
    </ul>
  </div>

  {% else %}
    <li class='login-account'><a href={% url 'users:login'%}>Войти в аккаунт</a> |
    <a href={% url 'users:register' %}>Регистрация</a></li>
  {% endif %}
    <h1 class='logo'></h1>
    
  </div>

  <div class='cscs'>
    {% if selected_brands %}
    <p class='selected_brands'>Выбранно:
        {% for brand in selected_brands %}
            {{ brand }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
{% endif %}

<div class='listbrannnns' onclick="toggleBrandSection()">
  <h2 class='brandss'>Бренды</h2>
</div>

<div id="brandSection" class="hidden"> 
  <form method="GET" action="{% url 'members:shop' %}">
    <ul class='list_brands'>
      {% if categories %}
        {% for category in categories %}
          <div> 
            <li>
              <label>
                <input type="checkbox" name="category" value="{{ category }}"
                  {% if category in selected_brands %} checked {% endif %}>
                {{ category }}
              </label>
            </li>
          </div>  
        {% endfor %}
      {% else %}
        <p>No categories found.</p>
      {% endif %}
    </ul>
    <button type="submit">Поиск</button>
  </form>
</div>

<div class='listbrannnn' onclick="toggleBrandSectio()">
  <h2 class='brandss'>Цвета</h2>
</div>


<div id="brandSectio" class="hidde"> 
  <form method="GET" action="{% url 'members:shop' %}">
    <ul class='list_brands'>
      {% for color in colors %}
        <div> 
          <li>
            <label>
              <input type="checkbox" name="color" value="{{ color }}"
                     {% if color in selected_colors %} checked {% endif %}>
              {{ color }}
            </label>
          </li>
        </div>
      {% endfor %}
    </ul>
    <button type="submit">Поиск</button>
  </form>
</div>
<!-- Hidden brand section -->
<div class='form-direction'>
  <form method="GET" action="{% url 'members:shop' %}">
    <input type="hidden" name="order" value="{{ ordering }}">
    {% for brand in selected_brands %}
      <input type="hidden" name="category" value="{{ brand }}">
    {% endfor %}
    {% for color in selected_colors %}
      <input type="hidden" name="color" value="{{ color }}">
    {% endfor %}
    <button class='button-direction' type="submit" name="direction" value="ascending">по возрастанию</button><hr class="unstyled">
    <button class='button-direction' type="submit" name="direction" value="descending">по убыванию</button>
  </form>
</div>

</div>

  <div class="container">
   


    {% for product in products %}
    
    <li class='shop'>
      
      <a href="{{ product.get_absolute_url }}">
        <div class='detail'>
          <img src="{{ product.picture }}">
        </div>  
          <h3 class='product-price'>{{ product.price }} $</h3>
        
 
        <h2>{{ product.name}}</h2>

      </a>   

    </li>
    {% endfor %}

  
    
</div>  

{% block navigation %}
{% if page_obj.has_other_pages %}
  <nav class='list-pages'>
    <ul>
      {% if page_obj.has_previous %}
        <li class='page-num'>
          <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
        </li>
      {% endif %}
      {% for p in paginator.page_range %}
      {% if page_obj.number == p %}
        <li class='page-num page-num-selected'>{{ p }}</li>
      {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
        <li class='page-num'> 
          <a href="?page={{ p }}">{{ p }}</a>
        </li>
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class='page-num'>
        <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
      </li>
    {% endif %}
    </ul>
  </nav>
{% endif %}
{% endblock %}
<footer>{% include 'footer.html' %}</footer>
{%endblock%}
</div>
</body>

<script>
var darkModeButton = document.getElementById('darkModeButton');
var body = document.body;

darkModeButton.addEventListener('click', function() {
  body.classList.toggle('dark-mode');
});

function toggleBrandSection() {
  var brandSection = document.getElementById('brandSection');
  brandSection.classList.toggle('hidden');
}

function toggleBrandSectio() {
  var brandSection = document.getElementById('brandSectio');
  brandSection.classList.toggle('hidde');
}


</script>
</html>