cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/add/<str:product_type>/', views.cart_add, name='cart_add'),
    path('cart/remove/<str:product_type>/', views.cart_remove, name='cart_remove'),
    path('cart/clear/', views.clear_cart, name='clear_cart'),
]

maindj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from members import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('users/', include('users.urls', namespace='users')),
    path('social-auth/', include('social_django.urls', namespace='social')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import include, path
from . import views
from .views import SheakersShopView, ShopListView, ShortsShopView, TShirtShopView
from django.views.decorators.cache import cache_page


app_name = 'members'

urlpatterns = [
      path('main/' , cache_page(60)(views.members), name='members'), 
     
      path('pay/', views.pay_system_view, name='pay'),
      path('not-auth/', views.not_auth, name='not_auth'),

      path('shop/', cache_page(10)(ShopListView.as_view()) , name='shop'),
      path('shop/<int:id>/<slug:slug>', views.product_detail_product,
         name='product_detail'),

      path('shop-tshirt/', cache_page(10)(TShirtShopView.as_view()), name='shop_tshirt'),
      path('shop-tshirt/<int:id>/<slug:slug>/', views.product_detail_product_tshirt,
           name='product_detail_tshirt'),

      path('shop-shorts/', cache_page(10)(ShortsShopView.as_view()), name='shop_shorts'),
      path('shop-shorts/<int:id>/<slug:slug>/', views.product_detail_shorts,
           name='product_detail_shorts'),

      path('shop-sneakers/', cache_page(10)(SheakersShopView.as_view()), name='shop_sneakers'),
      path('shop-sneakers/<int:id>/<slug:slug>/', views.product_detail_sneakers,
           name='product_detail_sneakers'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from members.models import Product, ProductShorts, ProductSneakers, ProductTshirt
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib.auth.decorators import login_required


@require_POST
def cart_add(request, product_type):
    cart = Cart(request)
    
    # Попытка найти продукт в модели Product
    try:
        product = Product.objects.get(product_type=product_type)
    except Product.DoesNotExist:
        # не найдено, попытка найти продукт в модели ProductTshirt
        try:
            product = ProductTshirt.objects.get(product_type=product_type)
        except ProductTshirt.DoesNotExist:
            # не найдено, попытка найти продукт в модели ProductShorts
            try:
                product = ProductShorts.objects.get(product_type=product_type)
            except ProductShorts.DoesNotExist:
                # попытка найти продукт в модели ProductSneakers      
                try:
                    product = ProductSneakers.objects.get(product_type=product_type)
                except ProductSneakers.DoesNotExist:
                    return JsonResponse({'success': False, 'message': 'Product not found.'})

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
        return JsonResponse({'success': True, 'message': 'Product added to cart.'})
    return JsonResponse({'success': False, 'message': 'Invalid form data.'})

 
def cart_remove(request, product_type):
    cart = Cart(request)
    
    # Попытка найти продукт в модели Product
    try:
        product = Product.objects.get(product_type=product_type)
    except Product.DoesNotExist:
        # Если не найдено, попытка найти продукт в модели ProductTshirt
        try:
            product = ProductTshirt.objects.get(product_type=product_type)
        except ProductTshirt.DoesNotExist:
            # Если не найдено, попытка найти продукт в модели ProductShorts
            try:
                product = ProductShorts.objects.get(product_type=product_type)
            except ProductShorts.DoesNotExist:
                try:
                    product = ProductSneakers.objects.get(product_type=product_type)
                except ProductSneakers.DoesNotExist:
                    return JsonResponse({'success': False, 'message': 'Product not found.'})

    cart.remove(product)
    return redirect('cart:cart_detail')


def clear_cart(request):
    cart = Cart(request)
    cart.remove_all()
    print("Cart cleared successfully")   # Отладочное сообщение
    return redirect('cart:cart_detail')


@login_required
def cart_detail(request):
    cart = Cart(request)
    cart_quantity = len(cart)

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart, 'cart_quantity': cart_quantity})

cart/templates/cart/detail.html
{% load static %}
<link href="{% static "cart.css" %}" rel="stylesheet">
<div class='headercont'>  
  <p ><a class='back' href="/shop/"> &lt; BACK</a></p>
  <div class='loggo'></div>

  <a href='/main/'><img class='loggo' src='/static/img/logobv.png' ></a>


  </div>
<div class='all'>


{% block content %}
  <h1>Корзина покупок</h1>
  <div class="cart">
    <div class='enddd'>
      <div class="total">
        <td>общая стоимость:</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </div>
    
  
  <p class="text-right">
    <a href="{% url 'members:shop' %}" class="button light">В магазин</a>
    <a href="{% url 'members:pay' %}" class="button">Оформить заказ</a>
  </p>
</div>

    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
        
          <div class='mainbody'>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img class='mainimg' src="{% if product.picture1 %}{{ product.picture1 }}{% else %} {% endif %}" width='150px' heigh='100px'>
              </a>
            </td>
            <div class='all_named'> 
              <div class=''>{{ product.category }}</div>
              <div class=''>{{ product.name }}</div>
              <div class=''>{{ product.color }}</div>
            </div>
    
            
            
            <td><a href="{% url 'cart:cart_remove' product_type=product.product_type %}">&#9587;</a></td>
            
            <div>
              {{ item.quantity }}
            </div>
            
            <td class="num">${{ item.total_price }}</td>
          </div>
          <form action="{% url 'cart:cart_add' product_type=product.product_type %}" method="post">
            {{ item.update_quantity_form.quantity }}
            {{ item.update_quantity_form.update }}
            <input type="submit" value="Обновить">
            {% csrf_token %}
          </form>
        {% endwith %}
        
      {% endfor %}
      <a href="{% url 'cart:clear_cart' %}">Очистить корзину</a>

      <footer>{% include 'footer.html' %}</footer>
</tbody>
</div>
</div>

  <footer>
    <div class='footer'>©wilmar.prodd<div>
  </footer>
{% endblock %}